### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by Alukard-X** [olsh/Feedly-Notifier#287] opened 2024-09-14 15:16 UTC
![image](https://github.com/user-attachments/assets/c191232a-f296-43e0-ab1a-b31562147426)
Chrome 129.0.6668.42
It happen

**Comment by Alukard-X** [comment] 2024-09-14 15:49
![image](https://github.com/user-attachments/assets/2d0fb9d8-26d4-4554-acc4-8a7cf824ffe3)

**Comment by olsh** [comment] 2024-09-14 19:35
Duplicate of https://github.com/olsh/Feedly-Notifier/issues/281

**Closed by olsh** 2024-09-14 19:35 UTC
Labels: bug
