### ISSUE TITLE
Number of Feedly Articles Incorrect and Won't Refresh/Update

### ISSUE THREAD

**Issue by ProgressRebeccaMurison** [olsh/Feedly-Notifier#55] opened 2016-09-06 16:26 UTC
Hello,

Feedly Notifier is showing I have 39 unread which is not the case, the number is close to 20, is there a quick fix for this?

Thanks.

**Comment by olsh** [comment] 2016-09-06 16:34
Hello, thanks for the feedback.

* Have you tried to re login? 
* Please make sure that you are using the same account on the site and extension.

**Comment by ProgressRebeccaMurison** [comment] 2016-09-06 16:39
Hello,

I have tried to logging out and logging back in, I have tried removing and reinstalling the extension, I have tried restarting my computer. I am sure I'm using the same account.

Quick note... I logged into Feedly itself in the browser and it looks like the problem is certain articles aren't populating the notifier. So the number is correct, but many of the articles aren't showing up.

**Comment by olsh** [comment] 2016-09-06 16:48
Well, I don't use the site, but I suppose it can be caused by paging or some "clever" sorting.
I didn't make changes in the counter-related code quite a long time ago.

**Comment by ProgressRebeccaMurison** [comment] 2016-09-06 16:59
Okay, I'll mess around and see if I can figured out the problem. Thank you

**Comment by olsh** [comment] 2016-09-10 11:58
I'm closing this.
Feel free to reopen the issue if you still have problems with the counter.

**Closed by olsh** 2016-09-10 11:58 UTC
