### ISSUE TITLE
Posts with no titles

### ISSUE THREAD

**Issue by tjesp** [olsh/Feedly-Notifier#158] opened 2020-02-02 19:51 UTC
I rarely experience a post on my rss feed that have no title. When I do I can't "click" anything to open the article. I wonder if you could make a fallback if there is no title so that there is something that is clickable?

**Comment by olsh** [comment] 2020-02-03 07:17
Hi @tjesp,

Thank you for the feedback.
Could you please provide an example of such an RSS feed?

**Comment by tjesp** [comment] 2020-02-03 07:33
The latest I saw was the latest post from

https://ildspor.wordpress.com/

It appears in my Feedly Notifier with no header and nowhere to click.

**Comment by olsh** [comment] 2020-02-03 18:17
I can't reproduce the issue at the moment; maybe it was a Feedly issue.
I won't close the issue; please ping me if you get an empty title again.
![image](https://user-images.githubusercontent.com/3613592/73678899-692b3980-46ca-11ea-9ea4-2ada035ffc2e.png)

**Comment by tjesp** [comment] 2020-02-03 18:18
Is there anything I can do at my end to help? Can I check if there are in-fact some characters in the title or can I do something else?

**Comment by olsh** [comment] 2020-02-03 18:38
Well, if you can familiar with developer tools, you can inspect the popup.
Also, the network inspection will be useful as well.
btw, which browser are you using?

**Closed** 2020-09-17 18:53 UTC

**Comment by olsh** [comment] 2020-09-17 19:11
Hey @tjesp ,

I managed to reproduce the issue. The issue should be fixed in the 2.25.3 version, please feel free to reopen the issue if you get empty titles again.
