### ISSUE TITLE
Customize CSS with Stylish in Chrome

### ISSUE THREAD

**Issue by CannyDuck** [olsh/Feedly-Notifier#98] opened 2017-07-12 19:54 UTC
I used Feedly Notfier with Firefox and was able to customize the popup CSS styles with Stylish. I switched over the Chrome and installed Stylish again, but unfortunately the CSS defined here is not applied to the Notifier extension popup. You have any idea how to customize the styles in Chrome?

**Comment by olsh** [comment] 2017-07-26 16:42
Hi @CannyDuck 
I'm not sure, but it seems like it's impossible to apply your CSS to another extension with Stylish.

**Comment by olsh** [comment] 2018-01-28 21:17
It seems like a duplicate of #115

**Closed by olsh** 2018-01-28 21:17 UTC
