### ISSUE TITLE
Popup window is broken

### ISSUE THREAD

**Issue by morawcik** [olsh/Feedly-Notifier#122] opened 2018-04-26 21:53 UTC
Hi
Starts from couple days ago most time when I'm trying open popup window it opens normal but then very fast switch to so small like 50x50px. There are a times when it opens normal and stay normal but it's like 20% from every opening.

![zrzut ekranu 2018-04-26 o 23 50 18](https://user-images.githubusercontent.com/4557530/39333893-eb31f986-49ac-11e8-8b43-c4d3a0128785.png)
![zrzut ekranu 2018-04-26 o 23 52 31](https://user-images.githubusercontent.com/4557530/39333894-eb4e0202-49ac-11e8-9e09-ec3e1997390d.png)

**Comment by olsh** [comment] 2018-04-26 21:55
Hi, could you please specify your browser?

**Comment by morawcik** [comment] 2018-04-26 22:02
Google Chrome was 65.* (not know details) and now 66.0.3359.139 - broken on both

**Comment by olsh** [comment] 2018-04-27 13:26
I can't reproduce this issue on Windows 10.
@morawcik are you using Mac too?

**Comment by morawcik** [comment] 2018-04-27 13:28
Yes, Mac OS X Sierra and High Sierra

**Comment by olsh** [comment] 2018-04-27 13:28
Probably related to 
https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/popup.js#L190-L193

I'll try to find a Mac to test.

**Comment by morawcik** [comment] 2018-05-06 20:32
What help?

I think that it can be this bug but I had this problem only with Feedly Notifier.

**Comment by madhur** [comment] 2018-05-07 04:09
I am having same issue.

<img width="121" alt="screen shot 2018-05-07 at 9 38 05 am" src="https://user-images.githubusercontent.com/509431/39684567-729f3ae8-51da-11e8-9698-d30e272f7bf1.png">

Running MAC OSX Sierra 10.12.6 

Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by olsh** [comment] 2018-05-07 07:48
Guys, if you can, please build the extension from the sources and play with the code (remove it, increase interval etc.):
https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/popup.js#L190-L193

Here are the build steps:
https://github.com/olsh/Feedly-Notifier#build

**Comment by olsh** [comment] 2018-05-07 08:25
Are you using the lastes keys for the sandbox?
https://groups.google.com/forum/#!topic/feedly-cloud/lvGXcO5uzas

**Comment by morawcik** [comment] 2018-05-07 08:26
Yes

**Comment by akaSybe** [comment] 2018-05-07 08:28
I'll take a look in the evening

**Comment by morawcik** [comment] 2018-05-07 08:36
But @olsh before removed this if statement even popup with login button was broken so maybe this is solution for all this problem?

**Comment by olsh** [comment] 2018-05-07 08:41
@morawcik just pushed a fix for the sandbox build, please rebuild the extension.

> But @olsh before removed this if statement even popup with login button was broken so maybe this is solution for all this problem?

Probably, but we need to test this. Here is the long thread about the issue:
https://github.com/olsh/Feedly-Notifier/issues/59

**Comment by morawcik** [comment] 2018-05-07 08:46
Thanks.
So removing if statement helps but it's not a solution - popup still resizing to small version but much less often.

**Comment by olsh** [comment] 2018-05-08 17:39
@morawcik how the testing is going, any issues?

Could you please send a PR if everything is ok?

**Comment by akaSybe** [comment] 2018-05-08 20:49
I increased timeout for Mac. New version will be available in store soon.

**Comment by morawcik** [comment] 2018-05-09 06:37
Nice, thanks @akaSybe 

Sorry @olsh I just back to home. It works great - no single problem :)

**Comment by olsh** [comment] 2018-05-09 08:37
Cool, I'm closing this issue out then.
Feel free to reopen it if you still have the bug.

**Closed by olsh** 2018-05-09 08:37 UTC
Labels: bug, chrome, help-wanted, mac
