### ISSUE TITLE
Works incorrectly in Firefox 61

### ISSUE THREAD

**Issue by zuber1979** [olsh/Feedly-Notifier#126] opened 2018-06-27 16:40 UTC
- does update until clicked
- does not clear saved, when unclicked

**Comment by olsh** [comment] 2018-06-27 19:51
Hi @zuber1979,

Can't reproduce on Windows 10.
Could you please check if there are errors in the FF console?

**Comment by wrooot** [comment] 2018-06-29 07:48
Works as intended for me also, Win7.

**Comment by olsh** [comment] 2018-06-29 08:28
Thanks, guys!
Closing this issue then, feel free to reopen it.

**Closed by olsh** 2018-06-29 08:28 UTC

**Comment by nugend** [comment] 2018-08-31 16:36
@olsh I'm having this issue on FF 61.0.2

I tend to leave my browser open for a week at a time. Might be some sort of timer issue?

**Comment by olsh** [comment] 2018-09-01 14:45
Hi, @nugend!

Well, probably it's a timer issue, but sadly I can't reproduce it :(
If this happens again, could you please check console errors?
