### ISSUE TITLE
Icons are not loaded

### ISSUE THREAD

**Issue by duoduobingbing** [olsh/Feedly-Notifier#206] opened 2022-04-08 11:37 UTC
**Describe the bug**
Small thumbnail icons are not loaded

**To Reproduce**
1. open add-on window
2. see posts without icons

**Expected behavior**
icons should be displayed

**Suspected Issue**
Using the option *Load this image in a different tab* reveals that the icon was supposed to be loaded from `https://i.olsh.me/icon?url=https://www.youtube.com&size=16..64..300&fallback_icon_url=https://www.google.com/s2/favicons?domain=https://www.youtube.com%26sz=64%26alt=feed`. The domain `i.olsh.me` seems to have expired thus causing the load of all small icons to fail

**Comment by olsh** [comment] 2022-04-08 11:49
Hi @duoduobingbing

olsh.me domain cannot be renewed because I'm Russian. Basically, I cannot renew it because of sanctions.
I'm transferring the domain to another registrar that is available for Russians.

**Comment by RejZoRSheep** [comment] 2022-04-10 08:37
> Hi @duoduobingbing
> 
> olsh.me domain cannot be renewed because I'm Russian. Basically, I cannot renew it because of sanctions. I'm transferring the domain to another registrar that is available for Russians.

I honestly wouldn't mind if you just add option to disable those icons entirely in the settings. So we can uncheck the option and just disable them entirely. Easier to live without the icons than knowing they are suppose to be there but aren't showing and you only see a placeholder spot...

**Comment by gwolf2u** [comment] 2022-04-11 19:10
why not simply use the fallback url?
https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/core.js#L734

**Comment by RejZoRSheep** [comment] 2022-04-13 06:11
> why not simply use the fallback url? https://github.com/olsh/Feedly-Notifier/blob/master/src/scripts/core.js#L734

Better question, why does it even have to parse icons from a 3rd party domain to begin with? Why not just use the source of the feed?

**Comment by olsh** [comment] 2022-04-13 07:25
Hi guys,

> why not simply use the fallback url?

Here are reasons why I set up a custom icon server
https://github.com/olsh/Feedly-Notifier/issues/163#issuecomment-614453428

> Better question, why does it even have to parse icons from a 3rd party domain to begin with? Why not just use the source of the feed?

What do you mean by `the source of the feed`?

**Comment by vahancho** [comment] 2022-04-13 08:08
Hi Oleg,

First of all, thank you for the great extension. I use to use it several years and was quite happy.
The resent changes are annoying of course - it's hard to see which item belongs to which feed, while icons were a good visual indication. IMO having a dummy icon or an icon with lower resolution is better than nothing. This ugly placeholder is really annoying.
What about this service: https://github.com/feedbin/feedbin-api/blob/master/content/icons.md ? Not sure how it works - just  randomly searched.

**Comment by duoduobingbing** [comment] 2022-04-13 18:34
@olsh Thanks for replying so quickly. 

One option would be to temporarily switch the icon loading to Google entirely and then switch back to a custom domain when there is one available. I guess most users would prefer the 16x16 icons over no icons at all for the time being.

Another option would be to switch to a `.ru`-Domain or use a Domain Registrar that allows anonymous (or for that matter non Visa/Mastercard dependent) payment with e.g. Bitcoin. [Namecheap](https://www.namecheap.com/support/payment/bitcoin/) seems supports Bitcoin payments.

**Comment by zoispag** [comment] 2022-04-14 12:56
> Hi guys,
> 
> Thank you for your help and kind words. I've migrated the domain to a new registrar. The icons should start working soon.

I can confirm they are now working! Thanks

**Closed** 2022-04-14 12:55 UTC
Labels: bug
